# Shared Application Properties
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Eureka Discovery Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Central Logback Configurations (Placeholder for central log properties)
logging.level.org.springframework=INFO
logging.level.com.genc=DEBUG
